//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgenciaLlamadaWeb
    {
        public int Id { get; set; }
        public string Agencia { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Exito { get; set; }
        public string CuerpoLlamada { get; set; }
        public string CuerpoRespuesta { get; set; }
        public string UrlLlamada { get; set; }
        public string TextoRespuestaError { get; set; }
        public string Usuario { get; set; }
    }
}
