//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApunteBancario
    {
        public ApunteBancario()
        {
            this.RegistroComplementarioConceptoes = new HashSet<RegistroComplementarioConcepto>();
            this.RegistroComplementarioEquivalencias = new HashSet<RegistroComplementarioEquivalencia>();
            this.ConciliacionBancariaPunteos = new HashSet<ConciliacionBancariaPunteo>();
        }
    
        public int Id { get; set; }
        public int FicheroCuaderno43Id { get; set; }
        public string ClaveOficinaOrigen { get; set; }
        public System.DateTime FechaOperacion { get; set; }
        public System.DateTime FechaValor { get; set; }
        public string ConceptoComun { get; set; }
        public string ConceptoPropio { get; set; }
        public string ClaveDebeOHaberMovimiento { get; set; }
        public decimal ImporteMovimiento { get; set; }
        public string NumeroDocumento { get; set; }
        public string Referencia1 { get; set; }
        public string Referencia2 { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual FicheroCuaderno43 FicheroCuaderno43 { get; set; }
        public virtual ICollection<RegistroComplementarioConcepto> RegistroComplementarioConceptoes { get; set; }
        public virtual ICollection<RegistroComplementarioEquivalencia> RegistroComplementarioEquivalencias { get; set; }
        public virtual ICollection<ConciliacionBancariaPunteo> ConciliacionBancariaPunteos { get; set; }
    }
}
