//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banco
    {
        public string Empresa { get; set; }
        public string Número { get; set; }
        public string Descripción { get; set; }
        public string Pais { get; set; }
        public string DC_IBAN { get; set; }
        public string Entidad { get; set; }
        public string Sucursal { get; set; }
        public string DC { get; set; }
        public string Nº_Cuenta { get; set; }
        public string BIC { get; set; }
        public string Cuenta_Contable { get; set; }
        public int NúmeroPagaré { get; set; }
        public string Fax { get; set; }
        public decimal GastosImpagado { get; set; }
        public decimal ImporteComisiónPorDevolucion { get; set; }
        public string DiarioImpagadoAutomatico { get; set; }
        public string CodigoConfirming { get; set; }
        public Nullable<short> TipoConfirming { get; set; }
        public decimal ImporteComisionDefecto { get; set; }
        public decimal ImporteCorreoImpagado { get; set; }
        public string DCConfirming { get; set; }
        public string Sufijo { get; set; }
        public decimal GastosRecibo { get; set; }
        public bool TieneIva { get; set; }
        public string CuentaGastosRecibo { get; set; }
        public decimal ImporteComisiónMáxImpagado { get; set; }
    }
}
