//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabAlquiler
    {
        public string Empresa { get; set; }
        public int Número { get; set; }
        public string Cliente { get; set; }
        public string Contacto { get; set; }
        public string Producto { get; set; }
        public string Inmovilizado { get; set; }
        public Nullable<int> Cuotas { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<System.DateTime> FechaSeñal { get; set; }
        public Nullable<decimal> ImporteSeñal { get; set; }
        public string NumeroSerie { get; set; }
        public string NombreProducto { get; set; }
        public string Familia { get; set; }
        public Nullable<bool> SeñalComisiona { get; set; }
        public Nullable<decimal> Indemnización { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<int> CabPedidoVta { get; set; }
        public string RutaContrato { get; set; }
        public string Comentarios { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaModificación { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Inmovilizado Inmovilizado1 { get; set; }
        public virtual Producto Producto1 { get; set; }
    }
}
