//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabAlbaranVta
    {
        public string Empresa { get; set; }
        public int Número { get; set; }
        public string Nº_Cliente { get; set; }
        public string Contacto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string PeriodoFacturación { get; set; }
        public string MotivoDevolución { get; set; }
        public string CodigoPostal { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empresa Empresa1 { get; set; }
    }
}
