//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabFacturaVta
    {
        public CabFacturaVta()
        {
            this.LinPedidoVtas = new HashSet<LinPedidoVta>();
        }
    
        public string Empresa { get; set; }
        public string Número { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Nº_Cliente { get; set; }
        public string Contacto { get; set; }
        public string Forma_Pago { get; set; }
        public string PlazosPago { get; set; }
        public string IVA { get; set; }
        public string Vendedor { get; set; }
        public string CCC { get; set; }
        public string Espejo { get; set; }
        public Nullable<System.DateTime> Primer_Vencimiento { get; set; }
        public string Serie { get; set; }
        public string Origen { get; set; }
        public string ContactoCobro { get; set; }
        public decimal NoComisiona { get; set; }
        public string Operador { get; set; }
        public string Cadena { get; set; }
        public short EstadoCliente { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    
        public virtual CCC CCC1 { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Empresa Empresa1 { get; set; }
        public virtual Empresa Empresa2 { get; set; }
        public virtual FormaPago FormasPago { get; set; }
        public virtual PlazoPago PlazosPago1 { get; set; }
        public virtual Vendedor Vendedore { get; set; }
        public virtual ICollection<LinPedidoVta> LinPedidoVtas { get; set; }
    }
}
