//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabPedidoVta
    {
        public CabPedidoVta()
        {
            this.LinPedidoVtas = new HashSet<LinPedidoVta>();
            this.VendedoresPedidoGrupoProductoes = new HashSet<VendedorPedidoGrupoProducto>();
        }
    
        public string Empresa { get; set; }
        public int Número { get; set; }
        public string Nº_Cliente { get; set; }
        public string Contacto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Forma_Pago { get; set; }
        public string PlazosPago { get; set; }
        public Nullable<System.DateTime> Primer_Vencimiento { get; set; }
        public string IVA { get; set; }
        public string Vendedor { get; set; }
        public string Comentarios { get; set; }
        public string ComentarioPicking { get; set; }
        public string Periodo_Facturacion { get; set; }
        public string Ruta { get; set; }
        public string Serie { get; set; }
        public string CCC { get; set; }
        public string Origen { get; set; }
        public bool Agrupada { get; set; }
        public string MotivoDevolución { get; set; }
        public string ContactoCobro { get; set; }
        public decimal NoComisiona { get; set; }
        public bool NotaEntrega { get; set; }
        public bool vtoBuenoPlazosPago { get; set; }
        public string Operador { get; set; }
        public bool FijarPrimerVto { get; set; }
        public bool MantenerJunto { get; set; }
        public bool ServirJunto { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    
        public virtual ICollection<LinPedidoVta> LinPedidoVtas { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<VendedorPedidoGrupoProducto> VendedoresPedidoGrupoProductoes { get; set; }
    }
}
