//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCC
    {
        public CCC()
        {
            this.Clientes = new HashSet<Cliente>();
            this.ExtractoClientes = new HashSet<ExtractoCliente>();
            this.CabFacturaVtas = new HashSet<CabFacturaVta>();
        }
    
        public string Empresa { get; set; }
        public string Cliente { get; set; }
        public string Contacto { get; set; }
        public string Número { get; set; }
        public string Pais { get; set; }
        public string DC_IBAN { get; set; }
        public string Entidad { get; set; }
        public string Oficina { get; set; }
        public string DC { get; set; }
        public string Nº_Cuenta { get; set; }
        public string BIC { get; set; }
        public short Estado { get; set; }
        public Nullable<short> TipoMandato { get; set; }
        public Nullable<System.DateTime> FechaMandato { get; set; }
        public string Secuencia { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Empresa Empresa1 { get; set; }
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual ICollection<ExtractoCliente> ExtractoClientes { get; set; }
        public virtual ICollection<CabFacturaVta> CabFacturaVtas { get; set; }
    }
}
