//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.CabPedidoVtas = new HashSet<CabPedidoVta>();
            this.Clientes1 = new HashSet<Cliente>();
            this.Clientes11 = new HashSet<Cliente>();
            this.Clientes12 = new HashSet<Cliente>();
            this.EnviosAgencias = new HashSet<EnviosAgencia>();
            this.LinPedidoVtas = new HashSet<LinPedidoVta>();
            this.CondPagoClientes = new HashSet<CondPagoCliente>();
            this.DescuentosClientes = new HashSet<DescuentosCliente>();
            this.DescuentosProductoes = new HashSet<DescuentosProducto>();
            this.DíasPagoClientes = new HashSet<DíasPagoClientes>();
            this.ExtractoProductoes = new HashSet<ExtractoProducto>();
            this.ExtractoClientes = new HashSet<ExtractoCliente>();
            this.CCCs = new HashSet<CCC>();
            this.PedidosEspeciales = new HashSet<PedidosEspeciale>();
            this.VendedoresClienteGrupoProductoes = new HashSet<VendedorClienteGrupoProducto>();
            this.SeguimientoClientes = new HashSet<SeguimientoCliente>();
            this.OfertasPermitidas = new HashSet<OfertaPermitida>();
        }
    
        public string Empresa { get; set; }
        public string Nº_Cliente { get; set; }
        public string Contacto { get; set; }
        public bool ClientePrincipal { get; set; }
        public string Nombre { get; set; }
        public string Dirección { get; set; }
        public string Población { get; set; }
        public string Teléfono { get; set; }
        public string Fax { get; set; }
        public string Vendedor { get; set; }
        public string Comentarios { get; set; }
        public string CodPostal { get; set; }
        public string CIF_NIF { get; set; }
        public string Provincia { get; set; }
        public Nullable<short> Estado { get; set; }
        public string IVA { get; set; }
        public string Grupo { get; set; }
        public string PeriodoFacturación { get; set; }
        public string CCC { get; set; }
        public string Ruta { get; set; }
        public byte NºCopiasAlbarán { get; set; }
        public byte NºCopiasFactura { get; set; }
        public string ComentarioRuta { get; set; }
        public string ComentarioPicking { get; set; }
        public bool GeneraBonificación { get; set; }
        public Nullable<decimal> RecargoPvp { get; set; }
        public string Web { get; set; }
        public bool BloquearPlazosPago { get; set; }
        public bool AvisarAntesCobro { get; set; }
        public string ContactoDefecto { get; set; }
        public string ContactoCobro { get; set; }
        public string ContactoBonificacion { get; set; }
        public bool AlbaranValorado { get; set; }
        public string Cadena { get; set; }
        public decimal NoComisiona { get; set; }
        public string Operador { get; set; }
        public string DiasEnServir { get; set; }
        public bool ServirJunto { get; set; }
        public bool MantenerJunto { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    
        public virtual ICollection<CabPedidoVta> CabPedidoVtas { get; set; }
        public virtual ICollection<Cliente> Clientes1 { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        public virtual ICollection<Cliente> Clientes11 { get; set; }
        public virtual Cliente Cliente2 { get; set; }
        public virtual ICollection<Cliente> Clientes12 { get; set; }
        public virtual Cliente Cliente3 { get; set; }
        public virtual Empresa Empresa1 { get; set; }
        public virtual ICollection<EnviosAgencia> EnviosAgencias { get; set; }
        public virtual ICollection<LinPedidoVta> LinPedidoVtas { get; set; }
        public virtual ICollection<CondPagoCliente> CondPagoClientes { get; set; }
        public virtual ICollection<DescuentosCliente> DescuentosClientes { get; set; }
        public virtual ICollection<DescuentosProducto> DescuentosProductoes { get; set; }
        public virtual ICollection<DíasPagoClientes> DíasPagoClientes { get; set; }
        public virtual ICollection<ExtractoProducto> ExtractoProductoes { get; set; }
        public virtual ICollection<ExtractoCliente> ExtractoClientes { get; set; }
        public virtual ICollection<CCC> CCCs { get; set; }
        public virtual CCC CCC1 { get; set; }
        public virtual ICollection<PedidosEspeciale> PedidosEspeciales { get; set; }
        public virtual ICollection<VendedorClienteGrupoProducto> VendedoresClienteGrupoProductoes { get; set; }
        public virtual Vendedor Vendedore { get; set; }
        public virtual ICollection<SeguimientoCliente> SeguimientoClientes { get; set; }
        public virtual ICollection<OfertaPermitida> OfertasPermitidas { get; set; }
    }
}
