//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodigoPostal
    {
        public CodigoPostal()
        {
            this.Clientes = new HashSet<Cliente>();
            this.Empresas = new HashSet<Empresa>();
            this.Proveedores = new HashSet<Proveedor>();
            this.VendedoresCodigoPostalGrupoProductoes = new HashSet<VendedorCodigoPostalGrupoProducto>();
        }
    
        public string Empresa { get; set; }
        public string Número { get; set; }
        public string Descripción { get; set; }
        public string Provincia { get; set; }
        public string Ruta { get; set; }
        public string Vendedor { get; set; }
    
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual Empresa Empresa1 { get; set; }
        public virtual ICollection<Empresa> Empresas { get; set; }
        public virtual ICollection<Proveedor> Proveedores { get; set; }
        public virtual ICollection<VendedorCodigoPostalGrupoProducto> VendedoresCodigoPostalGrupoProductoes { get; set; }
    }
}
