//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ComparativaAgenciaSombra
    {
        public int Id { get; set; }
        public int NumeroEnvio { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> Pedido { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string CodigoPostal { get; set; }
        public string Zona { get; set; }
        public decimal Peso { get; set; }
        public decimal Reembolso { get; set; }
        public int AgenciaRealId { get; set; }
        public string AgenciaRealNombre { get; set; }
        public Nullable<decimal> CosteReal { get; set; }
        public Nullable<int> AgenciaSombraId { get; set; }
        public string AgenciaSombraNombre { get; set; }
        public Nullable<decimal> CosteSombra { get; set; }
        public bool SombraGana { get; set; }
        public Nullable<decimal> Ahorro { get; set; }
        public System.DateTime FechaCalculo { get; set; }
    }
}
