//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConciliacionBancariaPunteo
    {
        public int Id { get; set; }
        public Nullable<int> ApunteBancoId { get; set; }
        public Nullable<int> ApunteContabilidadId { get; set; }
        public decimal ImportePunteado { get; set; }
        public string SimboloPunteo { get; set; }
        public Nullable<int> GrupoPunteo { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual ApunteBancario ApuntesBancario { get; set; }
    }
}
