//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlStock
    {
        public string Empresa { get; set; }
        public string Almacén { get; set; }
        public string Número { get; set; }
        public short StockMínimo { get; set; }
        public short StockMáximo { get; set; }
        public short Múltiplos { get; set; }
        public string Estacionalidad { get; set; }
        public string Categoria { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    }
}
