//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contabilidad
    {
        public string Empresa { get; set; }
        public int Nº_Orden { get; set; }
        public string TipoApunte { get; set; }
        public string Nº_Cuenta { get; set; }
        public string Concepto { get; set; }
        public decimal Debe { get; set; }
        public decimal Haber { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Nº_Documento { get; set; }
        public Nullable<int> Asiento { get; set; }
        public bool Asiento_Automático { get; set; }
        public Nullable<int> AsientoSecuencial { get; set; }
        public string Delegación { get; set; }
        public string FormaVenta { get; set; }
        public string Diario { get; set; }
        public string Origen { get; set; }
        public bool Punteado { get; set; }
        public string CentroCoste { get; set; }
        public string Departamento { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    
        public virtual PlanCuenta PlanCuenta { get; set; }
    }
}
