//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContadorGlobal
    {
        public int id { get; set; }
        public int Pedidos { get; set; }
        public int Albaranes { get; set; }
        public int Remesas { get; set; }
        public int Picking { get; set; }
        public int AlbaranesCmp { get; set; }
        public int PedidosCmp { get; set; }
        public int FacturasCmp { get; set; }
        public int TraspasoAlmacén { get; set; }
        public int Boletín { get; set; }
        public int Varios { get; set; }
        public int NotaEntrega { get; set; }
        public int Remesa { get; set; }
        public int Oferta { get; set; }
    }
}
