//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatoConfirming
    {
        public string Empresa { get; set; }
        public string Numero { get; set; }
        public string Contacto { get; set; }
        public string TipoDocumento { get; set; }
        public string FormaPago { get; set; }
        public bool BarradoCheque { get; set; }
        public string TipoEnvio { get; set; }
        public string IdiomaProveedor { get; set; }
        public string CodigoPaisDomicilio { get; set; }
        public string CodigoPaisDestino { get; set; }
        public string CodigoSwift { get; set; }
        public string CodigoIBAN { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Proveedor Proveedore { get; set; }
    }
}
