//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescuentosProducto
    {
        public string Empresa { get; set; }
        public int Nº_Orden { get; set; }
        public string Nº_Producto { get; set; }
        public string GrupoProducto { get; set; }
        public string Nº_Cliente { get; set; }
        public string Contacto { get; set; }
        public string NºProveedor { get; set; }
        public string ContactoProveedor { get; set; }
        public short CantidadMínima { get; set; }
        public decimal Descuento { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Familia { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
        public string FiltroProducto { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empresa Empresa1 { get; set; }
        public virtual Familia Familia1 { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Proveedor Proveedore { get; set; }
        public virtual GruposProducto GruposProducto { get; set; }
    }
}
