//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnviosAgencia
    {
        public int Numero { get; set; }
        public string Empresa { get; set; }
        public int Agencia { get; set; }
        public string Cliente { get; set; }
        public string Contacto { get; set; }
        public Nullable<int> Pedido { get; set; }
        public short Estado { get; set; }
        public System.DateTime Fecha { get; set; }
        public short Servicio { get; set; }
        public short Horario { get; set; }
        public short Bultos { get; set; }
        public short Retorno { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string CodPostal { get; set; }
        public string Poblacion { get; set; }
        public string Provincia { get; set; }
        public string Telefono { get; set; }
        public string Movil { get; set; }
        public string Email { get; set; }
        public string Observaciones { get; set; }
        public string Atencion { get; set; }
        public decimal Reembolso { get; set; }
        public Nullable<System.DateTime> FechaPagoReembolso { get; set; }
        public string CodigoBarras { get; set; }
        public string NombrePlaza { get; set; }
        public string Nemonico { get; set; }
        public string TelefonoPlaza { get; set; }
        public string EmailPlaza { get; set; }
        public string Vendedor { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public decimal ImporteGasto { get; set; }
        public Nullable<System.DateTime> FechaRetornoRecibido { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int Pais { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        public virtual Vendedor Vendedore { get; set; }
        public virtual EnvioAgenciaCoordenada EnviosAgenciaCoordenada { get; set; }
        public virtual CabPedidoVta CabPedidoVta { get; set; }
    }
}
