//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvioAgenciaCoordenada
    {
        public int EnvioAgenciaId { get; set; }
        public double Longitud { get; set; }
        public double Latitud { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string DireccionFormateada { get; set; }
    
        public virtual EnviosAgencia EnviosAgencia { get; set; }
    }
}
