//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvioHistoria
    {
        public int Numero { get; set; }
        public int NumeroEnvio { get; set; }
        public string Campo { get; set; }
        public string ValorAnterior { get; set; }
        public string Observaciones { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual EnviosAgencia EnviosAgencia { get; set; }
    }
}
