//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoPlanVentajas
    {
        public EstadoPlanVentajas()
        {
            this.PlanesVentajas = new HashSet<PlanVentajas>();
        }
    
        public int Numero { get; set; }
        public string Descripcion { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual ICollection<PlanVentajas> PlanesVentajas { get; set; }
    }
}
