//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    public partial class EventoSenal
    {
        public int Id { get; set; }
        public int EventoId { get; set; }
        public string Empresa { get; set; }
        public string Cliente { get; set; }
        public string Contacto { get; set; }
        public int NumOrdenExtracto { get; set; }
        public decimal Importe { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    }
}
