//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class FamiliaIncompatibilidad
    {
        public int Id { get; set; }
        public string Empresa { get; set; }
        public string Familia { get; set; }
        public string FamiliaIncompatible { get; set; }
        public int Meses { get; set; }
        public short Estado { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    }
}
