//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FicheroCuaderno43
    {
        public FicheroCuaderno43()
        {
            this.ApuntesBancarios = new HashSet<ApunteBancario>();
        }
    
        public int Id { get; set; }
        public string ClaveEntidad { get; set; }
        public string ClaveOficina { get; set; }
        public string NumeroCuenta { get; set; }
        public System.DateTime FechaInicial { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public string ClaveDebeOHaber { get; set; }
        public decimal ImporteSaldoInicial { get; set; }
        public string ClaveDivisa { get; set; }
        public string ModalidadInformacion { get; set; }
        public string NombreAbreviado { get; set; }
        public int NumeroApuntesDebe { get; set; }
        public decimal TotalImportesDebe { get; set; }
        public int NumeroApuntesHaber { get; set; }
        public decimal TotalImportesHaber { get; set; }
        public string CodigoSaldoFinal { get; set; }
        public decimal SaldoFinal { get; set; }
        public int NumeroRegistros { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual ICollection<ApunteBancario> ApuntesBancarios { get; set; }
    }
}
