//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GruposProducto
    {
        public GruposProducto()
        {
            this.DescuentosProductoes = new HashSet<DescuentosProducto>();
            this.ExtractoProductoes = new HashSet<ExtractoProducto>();
            this.Inventarios = new HashSet<Inventario>();
            this.LinPedidoVtas = new HashSet<LinPedidoVta>();
            this.PreExtrProductoes = new HashSet<PreExtrProducto>();
            this.Productos = new HashSet<Producto>();
            this.SubGruposProductoes = new HashSet<SubGruposProducto>();
            this.VendedoresClienteGrupoProductoes = new HashSet<VendedorClienteGrupoProducto>();
            this.VendedoresCodigoPostalGrupoProductoes = new HashSet<VendedorCodigoPostalGrupoProducto>();
            this.VendedoresPedidoGrupoProductoes = new HashSet<VendedorPedidoGrupoProducto>();
        }
    
        public string Empresa { get; set; }
        public string Número { get; set; }
        public string Descripción { get; set; }
        public string CtaVentas { get; set; }
        public string CtaAbonosVta { get; set; }
        public string CtaCompras { get; set; }
        public string CtaAbonosCmp { get; set; }
        public string CtaExistencias { get; set; }
        public string CtaVariación { get; set; }
        public string CtaDepreciación { get; set; }
        public string CtaDescuentos { get; set; }
        public string CtaDescuentosCmp { get; set; }
        public decimal C_Bonificación { get; set; }
        public string ProductoBonificación { get; set; }
        public bool AplicarDto { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    
        public virtual ICollection<DescuentosProducto> DescuentosProductoes { get; set; }
        public virtual Empresa Empresa1 { get; set; }
        public virtual ICollection<ExtractoProducto> ExtractoProductoes { get; set; }
        public virtual PlanCuenta PlanCuenta { get; set; }
        public virtual PlanCuenta PlanCuenta1 { get; set; }
        public virtual PlanCuenta PlanCuenta2 { get; set; }
        public virtual PlanCuenta PlanCuenta3 { get; set; }
        public virtual PlanCuenta PlanCuenta4 { get; set; }
        public virtual PlanCuenta PlanCuenta5 { get; set; }
        public virtual PlanCuenta PlanCuenta6 { get; set; }
        public virtual PlanCuenta PlanCuenta7 { get; set; }
        public virtual PlanCuenta PlanCuenta8 { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual ICollection<Inventario> Inventarios { get; set; }
        public virtual ICollection<LinPedidoVta> LinPedidoVtas { get; set; }
        public virtual ICollection<PreExtrProducto> PreExtrProductoes { get; set; }
        public virtual ICollection<Producto> Productos { get; set; }
        public virtual ICollection<SubGruposProducto> SubGruposProductoes { get; set; }
        public virtual ICollection<VendedorClienteGrupoProducto> VendedoresClienteGrupoProductoes { get; set; }
        public virtual ICollection<VendedorCodigoPostalGrupoProducto> VendedoresCodigoPostalGrupoProductoes { get; set; }
        public virtual ICollection<VendedorPedidoGrupoProducto> VendedoresPedidoGrupoProductoes { get; set; }
    }
}
