//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinFacturaVtaRectificacion
    {
        public string Empresa { get; set; }
        public string NumeroFactura { get; set; }
        public int NumeroLinea { get; set; }
        public string FacturaOriginalNumero { get; set; }
        public int FacturaOriginalLinea { get; set; }
        public decimal CantidadRectificada { get; set; }
    }
}
