//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiquidacionCliente
    {
        public string Empresa { get; set; }
        public int Nº_Orden { get; set; }
        public int Nº_Orden_Liq { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Importe { get; set; }
        public Nullable<int> Asiento { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
        public virtual ExtractoCliente ExtractoCliente { get; set; }
        public virtual ExtractoCliente ExtractoCliente1 { get; set; }
    }
}
