//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modificacion
    {
        public int id { get; set; }
        public string Tabla { get; set; }
        public string Anterior { get; set; }
        public string Nuevo { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
