//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoTPV
    {
        public int Id { get; set; }
        public string ModoCaptura { get; set; }
        public string Sesion { get; set; }
        public string Terminal { get; set; }
        public System.DateTime FechaCaptura { get; set; }
        public System.DateTime FechaOperacion { get; set; }
        public decimal ImporteOperacion { get; set; }
        public decimal ImporteComision { get; set; }
        public decimal ImporteAbono { get; set; }
        public string CodigoMoneda { get; set; }
        public string Comentarios { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
