//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiUsuario
    {
        public string Empresa { get; set; }
        public int Número { get; set; }
        public string Nombre { get; set; }
        public short Estado { get; set; }
        public string Máquina { get; set; }
        public Nullable<System.DateTime> FechaUltimaConexion { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaModificación { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
    }
}
