//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NVEntities : DbContext
    {
        public NVEntities()
            : base("name=NVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EnviosAgencia> EnviosAgencias { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<CabPedidoVta> CabPedidoVtas { get; set; }
        public virtual DbSet<LinPedidoVta> LinPedidoVtas { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Familia> Familias { get; set; }
        public virtual DbSet<SubGruposProducto> SubGruposProductoes { get; set; }
    }
}
