//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class NotaEntrega
    {
        [Key]
        [Column("NºOrden", Order = 0)]
        public int NºOrden { get; set; }

        [Key]
        [Column("NotaEntrega", Order = 1)]
        public int Numero { get; set; }

        public System.DateTime Fecha { get; set; }
    }
}
