//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificacionBuzon
    {
        public int Id { get; set; }
        public string Usuario { get; set; }
        public string Empresa { get; set; }
        public string Vendedor { get; set; }
        public string Cliente { get; set; }
        public string Contacto { get; set; }
        public string Aplicacion { get; set; }
        public string Titulo { get; set; }
        public string Cuerpo { get; set; }
        public string Datos { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaLeida { get; set; }
        public Nullable<System.DateTime> FechaEliminada { get; set; }
    }
}
