//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class OfertaEscalonadaProducto
    {
        public int Id { get; set; }
        public string Empresa { get; set; }
        public int OfertaId { get; set; }
        public string Producto { get; set; }
        public decimal PrecioBase { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }

        public virtual OfertaEscalonada OfertasEscalonada { get; set; }
        public virtual Producto Producto1 { get; set; }
    }
}
