//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoTPV
    {
        public PagoTPV()
        {
            this.PagosTPV_Efectos = new HashSet<PagoTPV_Efecto>();
        }
    
        public int Id { get; set; }
        public string NumeroOrden { get; set; }
        public string Tipo { get; set; }
        public string Empresa { get; set; }
        public string Cliente { get; set; }
        public string Contacto { get; set; }
        public decimal Importe { get; set; }
        public string Descripcion { get; set; }
        public string Correo { get; set; }
        public string Movil { get; set; }
        public string Estado { get; set; }
        public string CodigoRespuesta { get; set; }
        public string CodigoAutorizacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> ExtractoClienteId { get; set; }
        public string Documento { get; set; }
        public string Efecto { get; set; }
        public string Vendedor { get; set; }
        public string FormaVenta { get; set; }
        public string Delegacion { get; set; }
        public string TipoApunte { get; set; }
        public System.Guid TokenAcceso { get; set; }
        public Nullable<int> PagoOriginalId { get; set; }

        public virtual ICollection<PagoTPV_Efecto> PagosTPV_Efectos { get; set; }
    }
}
