//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoTPV_Efecto
    {
        public int Id { get; set; }
        public int IdPago { get; set; }
        public int ExtractoClienteId { get; set; }
        public decimal Importe { get; set; }
        public string Documento { get; set; }
        public string Efecto { get; set; }
        public string Contacto { get; set; }
        public string Vendedor { get; set; }
        public string FormaVenta { get; set; }
        public string Delegacion { get; set; }
        public string TipoApunte { get; set; }
    
        public virtual PagoTPV PagosTPV { get; set; }
    }
}
