//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosEspeciale
    {
        public string Empresa { get; set; }
        public int NºOrden { get; set; }
        public string EmpresaCmp { get; set; }
        public Nullable<int> NºPedidoVta { get; set; }
        public Nullable<int> NºOrdenVta { get; set; }
        public Nullable<int> NºOrdenCmp { get; set; }
        public Nullable<int> NºPedidoCmp { get; set; }
        public string NºCliente { get; set; }
        public string ContactoCliente { get; set; }
        public string NºProveedor { get; set; }
        public string ContactoProveedor { get; set; }
        public string Número { get; set; }
        public int Cantidad { get; set; }
        public bool Reponer { get; set; }
        public string Delegacion { get; set; }
        public Nullable<int> NºTraspaso { get; set; }
        public int NºVecesPedido { get; set; }
        public string Almacen { get; set; }
        public string Usuario { get; set; }
        public byte[] FechaModificacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual LinPedidoVta LinPedidoVta { get; set; }
        public virtual Proveedor Proveedore { get; set; }
    }
}
