//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanCuenta
    {
        public PlanCuenta()
        {
            this.Empresas = new HashSet<Empresa>();
            this.Empresas1 = new HashSet<Empresa>();
            this.Empresas2 = new HashSet<Empresa>();
            this.Empresas3 = new HashSet<Empresa>();
            this.Empresas4 = new HashSet<Empresa>();
            this.Empresas5 = new HashSet<Empresa>();
            this.Empresas6 = new HashSet<Empresa>();
            this.Empresas7 = new HashSet<Empresa>();
            this.Empresas8 = new HashSet<Empresa>();
            this.Empresas9 = new HashSet<Empresa>();
            this.ParámetrosIVA = new HashSet<ParametroIVA>();
            this.ParámetrosIVA1 = new HashSet<ParametroIVA>();
            this.ParámetrosIVA2 = new HashSet<ParametroIVA>();
            this.ParámetrosIVA3 = new HashSet<ParametroIVA>();
            this.Prepagos = new HashSet<Prepago>();
            this.Contabilidads = new HashSet<Contabilidad>();
            this.GruposProductoes = new HashSet<GruposProducto>();
            this.GruposProductoes1 = new HashSet<GruposProducto>();
            this.GruposProductoes2 = new HashSet<GruposProducto>();
            this.GruposProductoes3 = new HashSet<GruposProducto>();
            this.GruposProductoes4 = new HashSet<GruposProducto>();
            this.GruposProductoes5 = new HashSet<GruposProducto>();
            this.GruposProductoes6 = new HashSet<GruposProducto>();
            this.GruposProductoes7 = new HashSet<GruposProducto>();
            this.GruposProductoes8 = new HashSet<GruposProducto>();
        }
    
        public string Empresa { get; set; }
        public string Nº_Cuenta { get; set; }
        public string Concepto { get; set; }
        public string IVA { get; set; }
        public byte DebeHaber { get; set; }
        public bool SóloAuto { get; set; }
        public bool Bloqueada { get; set; }
        public short Estado { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    
        public virtual ICollection<Empresa> Empresas { get; set; }
        public virtual ICollection<Empresa> Empresas1 { get; set; }
        public virtual ICollection<Empresa> Empresas2 { get; set; }
        public virtual ICollection<Empresa> Empresas3 { get; set; }
        public virtual ICollection<Empresa> Empresas4 { get; set; }
        public virtual ICollection<Empresa> Empresas5 { get; set; }
        public virtual ICollection<Empresa> Empresas6 { get; set; }
        public virtual ICollection<Empresa> Empresas7 { get; set; }
        public virtual ICollection<Empresa> Empresas8 { get; set; }
        public virtual ICollection<Empresa> Empresas9 { get; set; }
        public virtual Empresa Empresa1 { get; set; }
        public virtual ICollection<ParametroIVA> ParámetrosIVA { get; set; }
        public virtual ICollection<ParametroIVA> ParámetrosIVA1 { get; set; }
        public virtual ICollection<ParametroIVA> ParámetrosIVA2 { get; set; }
        public virtual ICollection<ParametroIVA> ParámetrosIVA3 { get; set; }
        public virtual ICollection<Prepago> Prepagos { get; set; }
        public virtual ICollection<Contabilidad> Contabilidads { get; set; }
        public virtual ICollection<GruposProducto> GruposProductoes { get; set; }
        public virtual ICollection<GruposProducto> GruposProductoes1 { get; set; }
        public virtual ICollection<GruposProducto> GruposProductoes2 { get; set; }
        public virtual ICollection<GruposProducto> GruposProductoes3 { get; set; }
        public virtual ICollection<GruposProducto> GruposProductoes4 { get; set; }
        public virtual ICollection<GruposProducto> GruposProductoes5 { get; set; }
        public virtual ICollection<GruposProducto> GruposProductoes6 { get; set; }
        public virtual ICollection<GruposProducto> GruposProductoes7 { get; set; }
        public virtual ICollection<GruposProducto> GruposProductoes8 { get; set; }
    }
}
