//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanVentajas
    {
        public PlanVentajas()
        {
            this.PlanVentajasClientes = new HashSet<PlanVentajasCliente>();
        }
    
        public int Numero { get; set; }
        public string Empresa { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public decimal Importe { get; set; }
        public string Familia { get; set; }
        public int Estado { get; set; }
        public string Comentarios { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
        public virtual EstadoPlanVentajas EstadosPlanVentaja { get; set; }
        public virtual ICollection<PlanVentajasCliente> PlanVentajasClientes { get; set; }
    }
}
