//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlazoPago
    {
        public PlazoPago()
        {
            this.CondPagoClientes = new HashSet<CondPagoCliente>();
            this.Empresas = new HashSet<Empresa>();
        }
    
        public string Empresa { get; set; }
        public string Número { get; set; }
        public string Descripción { get; set; }
        public byte Nº_Plazos { get; set; }
        public byte DíasPrimerPlazo { get; set; }
        public byte DíasEntrePlazos { get; set; }
        public byte MesesPrimerPlazo { get; set; }
        public byte MesesEntrePlazos { get; set; }
        public decimal DtoProntoPago { get; set; }
        public bool Señal { get; set; }
        public Nullable<decimal> Financiacion { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    
        public virtual ICollection<CondPagoCliente> CondPagoClientes { get; set; }
        public virtual ICollection<Empresa> Empresas { get; set; }
        public virtual Empresa Empresa1 { get; set; }
    }
}
