//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreContabilidad
    {
        public string Empresa { get; set; }
        public int Nº_Orden { get; set; }
        public string TipoApunte { get; set; }
        public string TipoCuenta { get; set; }
        public string Nº_Cuenta { get; set; }
        public string Nº_Remesa { get; set; }
        public string Contacto { get; set; }
        public string Concepto { get; set; }
        public decimal Debe { get; set; }
        public decimal Haber { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Nº_Documento { get; set; }
        public string Efecto { get; set; }
        public Nullable<int> Asiento { get; set; }
        public string Diario { get; set; }
        public bool Asiento_Automático { get; set; }
        public string IVA_Cliente_Prov { get; set; }
        public string IVA_Producto { get; set; }
        public Nullable<decimal> ImporteIVA { get; set; }
        public string Delegación { get; set; }
        public string FormaVenta { get; set; }
        public Nullable<System.DateTime> FechaVto { get; set; }
        public string FormaPago { get; set; }
        public Nullable<decimal> ImporteApunte { get; set; }
        public string Vendedor { get; set; }
        public string CCC { get; set; }
        public string Contrapartida { get; set; }
        public Nullable<int> Liquidado { get; set; }
        public string Ruta { get; set; }
        public bool CajaLiquidada { get; set; }
        public string NºDocumentoProv { get; set; }
        public string CentroCoste { get; set; }
        public string Origen { get; set; }
        public string Departamento { get; set; }
        public string TipoRuta { get; set; }
        public Nullable<System.DateTime> FechaProveedor { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    }
}
