//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestashopProducto
    {
        public string Empresa { get; set; }
        public string Número { get; set; }
        public string Nombre { get; set; }
        public string DescripciónBreve { get; set; }
        public string Descripción { get; set; }
        public Nullable<decimal> PVP_IVA_Incluido { get; set; }
        public Nullable<bool> VistoBueno { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
