//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ProductoCodigoBarras
    {
        public int Id { get; set; }
        public string Empresa { get; set; }
        public string Producto { get; set; }
        public string Codigo { get; set; }
        public int Cantidad { get; set; }
        public string Proveedor { get; set; }
        public bool Principal { get; set; }
        public string Origen { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Activo { get; set; }
    }
}
