//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoCategoriaSecundaria
    {
        public string Empresa { get; set; }
        public string Número { get; set; }
        public int Orden { get; set; }
        public string Grupo { get; set; }
        public string SubGrupo { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual SubGruposProducto SubGruposProducto { get; set; }
    }
}
