//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedoresProducto
    {
        public string Empresa { get; set; }
        public string Nº_Proveedor { get; set; }
        public string ContactoProveedor { get; set; }
        public string Nº_Producto { get; set; }
        public string ReferenciaProv { get; set; }
        public short Orden { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Proveedor Proveedore { get; set; }
    }
}
