//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ReposicionCalendario
    {
        public int Id { get; set; }
        public string Empresa { get; set; }
        public string AlmacenOrigen { get; set; }
        public string AlmacenDestino { get; set; }
        public byte DiaSemana { get; set; }
        public System.TimeSpan HoraCierre { get; set; }
        public System.TimeSpan HoraLlegadaHabitual { get; set; }
        public bool Activo { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    }
}
