//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ReposicionTraspaso
    {
        public int Id { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> NumTraspaso { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public string Herramienta { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaCorte { get; set; }
        public string UsuarioPreparacion { get; set; }
        public Nullable<System.DateTime> FechaPreparada { get; set; }
        public string UsuarioRecepcion { get; set; }
        public Nullable<System.DateTime> FechaRecibida { get; set; }
    }
}
