//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruta
    {
        public Ruta()
        {
            this.ExtractoClientes = new HashSet<ExtractoCliente>();
            this.AgenciasTransportes = new HashSet<AgenciaTransporte>();
        }
    
        public string Empresa { get; set; }
        public string Número { get; set; }
        public string Descripción { get; set; }
        public bool Activa { get; set; }
        public int DiaReposicion { get; set; }
        public string Traspasar { get; set; }
        public decimal ImporteMinimo { get; set; }
        public string Copias { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
        public virtual ICollection<ExtractoCliente> ExtractoClientes { get; set; }
        public virtual ICollection<AgenciaTransporte> AgenciasTransportes { get; set; }
    }
}
