//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoCliente
    {
        public string Empresa { get; set; }
        public int NºOrden { get; set; }
        public string Número { get; set; }
        public string Contacto { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public string Vendedor { get; set; }
        public bool Pedido { get; set; }
        public bool ClienteNuevo { get; set; }
        public bool Aviso { get; set; }
        public bool Aparatos { get; set; }
        public bool DatosBanco { get; set; }
        public bool GestiónAparatos { get; set; }
        public bool PrimeraVisita { get; set; }
        public string Comentarios { get; set; }
        public short Estado { get; set; }
        public Nullable<int> NumOrdenExtracto { get; set; }
        public bool Cosmetica { get; set; }
        public bool PersonaQueDecide { get; set; }
        public bool PosibleVenta { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empresa Empresa1 { get; set; }
        public virtual Vendedor Vendedore { get; set; }
    }
}
