//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubGruposProducto
    {
        public SubGruposProducto()
        {
            this.LinPedidoVtas = new HashSet<LinPedidoVta>();
            this.Productos = new HashSet<Producto>();
            this.Inventarios = new HashSet<Inventario>();
        }
    
        public string Empresa { get; set; }
        public string Grupo { get; set; }
        public string Número { get; set; }
        public string Descripción { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
    
        public virtual ICollection<LinPedidoVta> LinPedidoVtas { get; set; }
        public virtual ICollection<Producto> Productos { get; set; }
        public virtual ICollection<Inventario> Inventarios { get; set; }
    }
}
