//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncMessageRetry
    {
        public string MessageId { get; set; }
        public string Tabla { get; set; }
        public string EntityId { get; set; }
        public string Source { get; set; }
        public int AttemptCount { get; set; }
        public System.DateTime FirstAttemptDate { get; set; }
        public System.DateTime LastAttemptDate { get; set; }
        public string LastError { get; set; }
        public string Status { get; set; }
        public string MessageData { get; set; }
    }
}
