//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public string Empresa { get; set; }
        public int NºOrden { get; set; }
        public string EmpresaAlbaranVta { get; set; }
        public string EmpresaAlbaranCmp { get; set; }
        public string Almacén { get; set; }
        public string Número { get; set; }
        public int Cantidad { get; set; }
        public string Pasillo { get; set; }
        public string Fila { get; set; }
        public string Columna { get; set; }
        public Nullable<int> PedidoVta { get; set; }
        public Nullable<int> AlbaránVta { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> NºOrdenVta { get; set; }
        public Nullable<int> PedidoCmp { get; set; }
        public Nullable<int> AlbaránCmp { get; set; }
        public Nullable<int> NºOrdenCmp { get; set; }
        public Nullable<int> NºTraspasoInv { get; set; }
        public Nullable<int> NºOrdenRepo { get; set; }
        public Nullable<int> NºTraspasoRepo { get; set; }
        public Nullable<int> NºTraspaso { get; set; }
        public string Usuario { get; set; }
        public byte[] FechaModificación { get; set; }
        public System.DateTime FechaCreación { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
    }
}
