//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class VerifactuRegistro
    {
        public int Id { get; set; }
        public string Empresa { get; set; }
        public string NumeroFactura { get; set; }
        public string TipoRegistro { get; set; }
        public string RechazoPrevio { get; set; }
        public string Payload { get; set; }
        public string RespuestaUuid { get; set; }
        public string RespuestaEstado { get; set; }
        public string RespuestaError { get; set; }
        public bool Exitoso { get; set; }
        public System.DateTime FechaEnvio { get; set; }
        public string Usuario { get; set; }
    }
}
