//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public Video()
        {
            this.VideosProductos = new HashSet<VideoProducto>();
        }
    
        public int Id { get; set; }
        public string VideoId { get; set; }
        public string Transcripcion { get; set; }
        public string Descripcion { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public string Protocolo { get; set; }
        public bool EsUnProtocolo { get; set; }
    
        public virtual ICollection<VideoProducto> VideosProductos { get; set; }
    }
}
