//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoProducto
    {
        public int Id { get; set; }
        public int VideoId { get; set; }
        public string NombreProducto { get; set; }
        public string Referencia { get; set; }
        public string Enlace { get; set; }
        public string TiempoAparicion { get; set; }
        public string EnlaceTienda { get; set; }
        public string EnlaceVideo { get; set; }
    
        public virtual Video Video { get; set; }
    }
}
