//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vstLinPedidoVtaComisione
    {
        public int Nº_Orden { get; set; }
        public string Empresa { get; set; }
        public string Nº_Cliente { get; set; }
        public string Contacto { get; set; }
        public string Vendedor { get; set; }
        public string Ruta { get; set; }
        public string Nombre { get; set; }
        public string Dirección { get; set; }
        public string CodPostal { get; set; }
        public string Población { get; set; }
        public int Número { get; set; }
        public string Producto { get; set; }
        public string Texto { get; set; }
        public string Familia { get; set; }
        public System.DateTime Fecha_Entrega { get; set; }
        public Nullable<short> Cantidad { get; set; }
        public short Estado { get; set; }
        public Nullable<int> Picking { get; set; }
        public decimal Base_Imponible { get; set; }
        public Nullable<System.DateTime> Fecha_Albarán { get; set; }
        public Nullable<int> Nº_Albarán { get; set; }
        public Nullable<System.DateTime> Fecha_Factura { get; set; }
        public string Nº_Factura { get; set; }
        public string Grupo { get; set; }
        public string SubGrupo { get; set; }
        public Nullable<short> EstadoFamilia { get; set; }
    }
}
