-- NestoAPI#596 (decisión 1, OK de Carlos 06/10/26): clientes activos con código postal de 4 cifras y país ES que en
-- realidad son de otro país (la población/provincia lo dice). País ISO-2 propuesto por las palabras de la ficha: REVISAR
-- la columna de comentario antes de lanzar. Lanzar como sa en NV. Idempotente.
SET NOCOUNT ON;
BEGIN TRAN;
UPDATE Clientes SET Pais = 'PT' WHERE Empresa = '1' AND [Nº Cliente] = '27948' AND Contacto = '0' AND RTRIM(CodPostal) = '9600' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- 075 RIBEIRA GRANDE / PORTUGAL (ALVARO LEMOS)
UPDATE Clientes SET Pais = 'PT' WHERE Empresa = '1' AND [Nº Cliente] = '22632' AND Contacto = '0' AND RTRIM(CodPostal) = '3860' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- 530 ESTARREJA / PORTUGAL (BRUNO OSVALDO CASTRO ABREU FREIRE)
UPDATE Clientes SET Pais = 'NL' WHERE Empresa = '1' AND [Nº Cliente] = '20828' AND Contacto = '0' AND RTRIM(CodPostal) = '1069' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- AMSTERDAM / HOLANDA (PATRICIA GARZÓN OSPINA)
UPDATE Clientes SET Pais = 'BE' WHERE Empresa = '1' AND [Nº Cliente] = '32325' AND Contacto = '0' AND RTRIM(CodPostal) = '2020' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- ANTWERPEN / BÉLGICA (MUÑOZ GONZALEZ)
UPDATE Clientes SET Pais = 'BE' WHERE Empresa = '1' AND [Nº Cliente] = '32335' AND Contacto = '0' AND RTRIM(CodPostal) = '2020' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- ANTWERPEN / BÉLGICA (MUÑOZ GONZÁLEZ)
UPDATE Clientes SET Pais = 'PT' WHERE Empresa = '1' AND [Nº Cliente] = '18783' AND Contacto = '0' AND RTRIM(CodPostal) = '2835' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- BAIXA DA BANHEIRA 023 / PORTUGAL (CARMO CABELEIREIRO LDA.)
UPDATE Clientes SET Pais = 'BE' WHERE Empresa = '1' AND [Nº Cliente] = '16720' AND Contacto = '1' AND RTRIM(CodPostal) = '2000' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- BELGIUM / ANTWERP (THU HUONG VU PHAM BTW BE0562903074)
UPDATE Clientes SET Pais = 'CH' WHERE Empresa = '1' AND [Nº Cliente] = '24444' AND Contacto = '1' AND RTRIM(CodPostal) = '3006' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- BERN / SUIZA (ELSA CONTANZA ROMERO)
UPDATE Clientes SET Pais = 'CH' WHERE Empresa = '1' AND [Nº Cliente] = '31573' AND Contacto = '0' AND RTRIM(CodPostal) = '2555' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- BERNE / BRÜGG/BE (BELLINO7777)
UPDATE Clientes SET Pais = 'CO' WHERE Empresa = '1' AND [Nº Cliente] = '15625' AND Contacto = '0' AND RTRIM(CodPostal) = '5897' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- BOGOTÁ / COLOMBIA (GEOFFREY HILL ROJAS YEPES)
UPDATE Clientes SET Pais = 'PT' WHERE Empresa = '1' AND [Nº Cliente] = '16945' AND Contacto = '0' AND RTRIM(CodPostal) = '5300' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- BRAGANÇA / PORTUGAL (ANTONIO ALBERTO GONÇALVES COELHO)
UPDATE Clientes SET Pais = 'PT' WHERE Empresa = '1' AND [Nº Cliente] = '23982' AND Contacto = '0' AND RTRIM(CodPostal) = '1685' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- CANECAS / PORTUGAL (FATIMA ALMEIDA)
UPDATE Clientes SET Pais = 'PT' WHERE Empresa = '1' AND [Nº Cliente] = '26192' AND Contacto = '0' AND RTRIM(CodPostal) = '3140' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- COIMBRA-PEREIRA / PORTUGAL (CLÁUDI ANTUNES)
UPDATE Clientes SET Pais = 'CH' WHERE Empresa = '1' AND [Nº Cliente] = '28341' AND Contacto = '0' AND RTRIM(CodPostal) = '1246' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- CORSIER / SUIZA (MARYAN MAKSYMOVYCH)
UPDATE Clientes SET Pais = 'LU' WHERE Empresa = '1' AND [Nº Cliente] = '40288' AND Contacto = '1' AND RTRIM(CodPostal) = '4720' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- Differdange / Luxemburgo (MACIAS TROYA KERLY TRINIDAD)
UPDATE Clientes SET Pais = 'LU' WHERE Empresa = '1' AND [Nº Cliente] = '40298' AND Contacto = '1' AND RTRIM(CodPostal) = '4720' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- DIFFERDANGE / LUXEMBURGO (KERLY TRINIDAD MACIAS TROYA)
UPDATE Clientes SET Pais = 'PT' WHERE Empresa = '1' AND [Nº Cliente] = '27313' AND Contacto = '0' AND RTRIM(CodPostal) = '2765' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- ESTORIL / PORTUGAL (SARA BOLIN DOMECQ)
UPDATE Clientes SET Pais = 'BE' WHERE Empresa = '1' AND [Nº Cliente] = '41683' AND Contacto = '0' AND RTRIM(CodPostal) = '1040' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- ETTERBEEK / BÉLGICA (TOWE, TATIANA)
UPDATE Clientes SET Pais = 'BE' WHERE Empresa = '1' AND [Nº Cliente] = '31170' AND Contacto = '0' AND RTRIM(CodPostal) = '6240' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- FARCIENNES CHARLEROI / BELGIQUE (GIOVANNA CONFORTI)
UPDATE Clientes SET Pais = 'AT' WHERE Empresa = '1' AND [Nº Cliente] = '32263' AND Contacto = '0' AND RTRIM(CodPostal) = '6800' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- FELDKIRCH / AUSTRIA (MARIA CRISTINA MAGYANI)
UPDATE Clientes SET Pais = 'CH' WHERE Empresa = '1' AND [Nº Cliente] = '25755' AND Contacto = '0' AND RTRIM(CodPostal) = '2046' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- FONTAINES / NE (SUIZA) (PIEMONTESI SANCHEZ CLARA)
UPDATE Clientes SET Pais = 'CH' WHERE Empresa = '1' AND [Nº Cliente] = '2781' AND Contacto = '0' AND RTRIM(CodPostal) = '1204' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- GINEBRA / GINEBRA (EMMA TARRE CAPELLADES)
UPDATE Clientes SET Pais = 'AT' WHERE Empresa = '1' AND [Nº Cliente] = '32425' AND Contacto = '0' AND RTRIM(CodPostal) = '8042' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- GRAZ / STEIERMARK (JONATHAN SIVAK)
UPDATE Clientes SET Pais = 'CH' WHERE Empresa = '1' AND [Nº Cliente] = '24444' AND Contacto = '0' AND RTRIM(CodPostal) = '3063' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- ITTIGEN / SUIZA (ELSA CONSTANZA ROMERO)
UPDATE Clientes SET Pais = 'BE' WHERE Empresa = '1' AND [Nº Cliente] = '33991' AND Contacto = '0' AND RTRIM(CodPostal) = '1050' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- IXELLES / BELGIQUE (BEZZUBIK, ALICJA)
UPDATE Clientes SET Pais = 'CH' WHERE Empresa = '1' AND [Nº Cliente] = '33925' AND Contacto = '0' AND RTRIM(CodPostal) = '1254' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- JUSSY / SUIZA (ISLENA SIMONET)
UPDATE Clientes SET Pais = 'MA' WHERE Empresa = '1' AND [Nº Cliente] = '39225' AND Contacto = '0' AND RTRIM(CodPostal) = '1400' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- KENITRA / MARRUECOS (SARA EL HAJJOUJI LAZHAR)
UPDATE Clientes SET Pais = 'CY' WHERE Empresa = '1' AND [Nº Cliente] = '31265' AND Contacto = '0' AND RTRIM(CodPostal) = '4532' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- LIMASSOL / CYPRUS (NATALIA TRETYAKOVA)
UPDATE Clientes SET Pais = 'PT' WHERE Empresa = '1' AND [Nº Cliente] = '21094' AND Contacto = '0' AND RTRIM(CodPostal) = '1300' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- LISBOA 1300 151 / PORTUGAL (RUBÉN ORNELAS)
UPDATE Clientes SET Pais = 'AO' WHERE Empresa = '1' AND [Nº Cliente] = '24217' AND Contacto = '0' AND RTRIM(CodPostal) = '3521' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- LUANDA / ANGOLA (NOVA AURA - LDA)
UPDATE Clientes SET Pais = 'BE' WHERE Empresa = '1' AND [Nº Cliente] = '33932' AND Contacto = '0' AND RTRIM(CodPostal) = '4623' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- MAGNÉE / BÉLGICA (MADZ, SRL.)
UPDATE Clientes SET Pais = 'PT' WHERE Empresa = '1' AND [Nº Cliente] = '27502' AND Contacto = '0' AND RTRIM(CodPostal) = '4470' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- MAIA / PORTUGAL (OSVALDO GOMES)
UPDATE Clientes SET Pais = 'VE' WHERE Empresa = '1' AND [Nº Cliente] = '32622' AND Contacto = '0' AND RTRIM(CodPostal) = '4001' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- MARACAIBO / VENEZUELA (SOR ANGELA LUZARDO)
UPDATE Clientes SET Pais = 'BE' WHERE Empresa = '1' AND [Nº Cliente] = '33990' AND Contacto = '0' AND RTRIM(CodPostal) = '5640' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- METTET / BÉLGICA (MICELLO AURORE)
UPDATE Clientes SET Pais = 'PT' WHERE Empresa = '1' AND [Nº Cliente] = '22382' AND Contacto = '0' AND RTRIM(CodPostal) = '2665' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- MILHARADO / LISBOA (INÊS FILIPA COELHO DOS SANTOS)
UPDATE Clientes SET Pais = 'AT' WHERE Empresa = '1' AND [Nº Cliente] = '32380' AND Contacto = '0' AND RTRIM(CodPostal) = '8680' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- MUERZZUSCHLAG / STEEIERMARK (MARTINA ALMER)
UPDATE Clientes SET Pais = 'PT' WHERE Empresa = '1' AND [Nº Cliente] = '22429' AND Contacto = '0' AND RTRIM(CodPostal) = '3025' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- PEDRULHA(COIMBRA) / PORTUGAL (PAULA FERNANDES)
UPDATE Clientes SET Pais = 'BE' WHERE Empresa = '1' AND [Nº Cliente] = '33960' AND Contacto = '0' AND RTRIM(CodPostal) = '4280' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- POUCET / BÉLGICA (DELWICHE LARA)
UPDATE Clientes SET Pais = 'EC' WHERE Empresa = '1' AND [Nº Cliente] = '9624' AND Contacto = '0' AND RTRIM(CodPostal) = '0951' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- QUITO / PICHINCHA (CARLOS AUGUSTO SANCHEZ AGUIRRE)
UPDATE Clientes SET Pais = 'EC' WHERE Empresa = '1' AND [Nº Cliente] = '9792' AND Contacto = '0' AND RTRIM(CodPostal) = '0951' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- QUITO / ECUADOR (MIRIAN VERA LOPEZ)
UPDATE Clientes SET Pais = 'BE' WHERE Empresa = '1' AND [Nº Cliente] = '32488' AND Contacto = '0' AND RTRIM(CodPostal) = '1030' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- SCHAERBEEK / BRUSELAS (YESENIA ANDREA AVILA QUEVEDO)
UPDATE Clientes SET Pais = 'BE' WHERE Empresa = '1' AND [Nº Cliente] = '33975' AND Contacto = '0' AND RTRIM(CodPostal) = '4537' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- SERAING-LE-CHÂTEAU / LIÈGE (SRL DSVET SOPHIE DUMONT)
UPDATE Clientes SET Pais = 'BE' WHERE Empresa = '1' AND [Nº Cliente] = '38394' AND Contacto = '0' AND RTRIM(CodPostal) = '1180' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- UCCLE / BÉLGICA (SRL TWINS O)
UPDATE Clientes SET Pais = 'CH' WHERE Empresa = '1' AND [Nº Cliente] = '32889' AND Contacto = '0' AND RTRIM(CodPostal) = '1936' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- VERBIER / VALAIS (NICOLA SIMCOCK)
UPDATE Clientes SET Pais = 'AT' WHERE Empresa = '1' AND [Nº Cliente] = '32312' AND Contacto = '0' AND RTRIM(CodPostal) = '1150' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- VIENNA / AUSTRIA (EMILIA GEORGEVICI)
UPDATE Clientes SET Pais = 'PT' WHERE Empresa = '1' AND [Nº Cliente] = '9125' AND Contacto = '0' AND RTRIM(CodPostal) = '6355' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- VILAR FORMOSO / PORTUGAL (SUGEY RAMIREZ GODOY)
UPDATE Clientes SET Pais = 'AT' WHERE Empresa = '1' AND [Nº Cliente] = '32361' AND Contacto = '0' AND RTRIM(CodPostal) = '1220' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- WEIN / AUSTRIA (MELANIE LEITNER)
UPDATE Clientes SET Pais = 'BE' WHERE Empresa = '1' AND [Nº Cliente] = '29567' AND Contacto = '0' AND RTRIM(CodPostal) = '1150' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- WOLUWE SAINT PIERRE / BRUXELLE - BELGIQUE (THU HUONG VU PHAM)
UPDATE Clientes SET Pais = 'CH' WHERE Empresa = '1' AND [Nº Cliente] = '31842' AND Contacto = '0' AND RTRIM(CodPostal) = '4465' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- ZUNZGEN / SISSACH (STEPHANIE TRAINA)
UPDATE Clientes SET Pais = 'CH' WHERE Empresa = '1' AND [Nº Cliente] = '20230' AND Contacto = '0' AND RTRIM(CodPostal) = '8003' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')); -- ZURICH / SUIZA (KOSMETIC MATILDE)
-- Comprobación: tiene que quedar a 0
SELECT COUNT(*) AS QuedanConES FROM Clientes WHERE Empresa='1' AND Estado>=0 AND LEN(RTRIM(CodPostal))=4 AND CodPostal LIKE '[0-9][0-9][0-9][0-9]%' AND (Pais IS NULL OR RTRIM(Pais) IN ('ES','')) AND RTRIM(Provincia) NOT IN ('');
-- Si todo cuadra: COMMIT; si no: ROLLBACK
COMMIT;
